# Data source configuration for threat intelligence queries
# Each source defines a KQL query against Log Analytics and output settings

# Geo enrichment provider: "maxmind" (full coordinates) or "azure_maps" (country-only)
# MaxMind requires: MAXMIND_LICENSE_KEY from Key Vault or environment variable
# Azure Maps requires: AZURE_MAPS_SUBSCRIPTION_KEY environment variable
geo_provider: "maxmind"  # Options: "maxmind", "azure_maps"

# Key Vault settings (optional - falls back to environment variables)
key_vault_name: ""  # e.g., "kv-sentinel-maps" - leave empty to use env vars

sources:
  - id: signin_failures
    name: "Sign-in Failures"
    enabled: false  # Disabled - template example only
    refresh_interval_seconds: 300  # 5 minutes
    query_time_window_hours: 24
    incremental: true
    incremental_overlap_minutes: 10
    output_filename: "signin-failures.tsv"
    kql_query: |
      SigninLogs
      | where TimeGenerated >= ago({time_window}h)
      | where ResultType != "0"  // Failed sign-ins
      | extend Country = tostring(LocationDetails.countryOrRegion)
      | extend City = tostring(LocationDetails.city)
      | extend IPAddress = tostring(IPAddress)
      | project TimeGenerated, UserPrincipalName, IPAddress, Country, City, ResultType, ResultDescription
      | order by TimeGenerated desc
    columns:
      - TimeGenerated
      - UserPrincipalName
      - IPAddress
      - Country
      - City
      - ResultType
      - ResultDescription

  - id: threat_intel_indicators
    name: "Threat Intelligence Indicators"
    enabled: true
    refresh_threshold_hours: 24  # Refresh if file older than this (configurable)
    query_time_window_hours: 360  # 15 days (initial lookback and max refresh window)
    incremental: true
    incremental_overlap_minutes: 30
    output_filename: "threat-intel-indicators.tsv"
    auto_enrich_geo: true  # Automatically enrich with geolocation after refresh
    auto_generate_geojson: true  # Automatically generate GeoJSON after geo enrichment
    kql_query: |
      ThreatIntelIndicators
      | extend Description = Data.description
      | extend Type = parse_json(tostring(Data.indicator_types))[0]
      | extend Label = parse_json(tostring(Data.labels))[0]
      | summarize arg_max(TimeGenerated, *) by ObservableValue
      | where Pattern contains "network"
      | project TimeGenerated, ObservableValue, SourceSystem, Type, Label, Confidence, Description, Created, IsActive
      | order by TimeGenerated desc
    columns:
      - TimeGenerated
      - ObservableValue
      - SourceSystem
      - Type
      - Label
      - Confidence
      - Description
      - Created
      - IsActive
      - Latitude
      - Longitude
      - Country
      - City
